-- Initial PostgreSQL schema for the Modbus backend.
--
-- Ported from the live Oracle XE schema (26 tables) during the Oracle -> Postgres
-- migration. Column types, defaults, and constraints mirror the Oracle originals
-- except where Postgres has a native, simpler equivalent:
--   - identity columns replace Oracle's implicit ISEQ$$ sequences AND the four
--     explicit sequences (device_action_seq, device_reading_seq, alarm_seq,
--     alarm_ack_seq) that db.js used to manage by hand with a
--     "create if missing, else MAX()+1" fallback — Postgres needs none of that.
--   - `devices.device_id` is deliberately NOT an identity column: the app
--     allocates it manually (NVL(MAX(device_id),0)+1, see datakom-sync.js and
--     index.js) because the Oracle table never had a sequence either.
--
-- Run once against a fresh database: `psql "$DATABASE_URL" -f 001_init.sql`.
-- Every statement is idempotent (IF NOT EXISTS) so re-running is safe.

CREATE TABLE IF NOT EXISTS users (
  user_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username            VARCHAR(60) NOT NULL,
  email               VARCHAR(255) NOT NULL,
  password_hash       VARCHAR(255) NOT NULL,
  full_name           VARCHAR(120),
  status              VARCHAR(20) NOT NULL DEFAULT 'active',
  failed_logins       INTEGER NOT NULL DEFAULT 0,
  locked_until        TIMESTAMP,
  last_login_at       TIMESTAMP,
  password_changed_at TIMESTAMP DEFAULT NOW(),
  created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_users_email    UNIQUE (email),
  CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS roles (
  role_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_key           VARCHAR(40) NOT NULL,
  role_name          VARCHAR(80) NOT NULL,
  description        VARCHAR(255),
  is_system          INTEGER NOT NULL DEFAULT 0,
  created_at         TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP NOT NULL DEFAULT NOW(),
  scope_level        VARCHAR(20) NOT NULL DEFAULT 'global',
  scope_project_id   INTEGER,
  scope_location_id  INTEGER,
  scope_device_id    INTEGER,
  scope_count        INTEGER DEFAULT 1,
  CONSTRAINT uq_roles_role_key UNIQUE (role_key)
);

CREATE TABLE IF NOT EXISTS permissions (
  permission_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_key VARCHAR(80) NOT NULL,
  description    VARCHAR(255),
  created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
  resource_type  VARCHAR(40),
  access_level   VARCHAR(40),
  CONSTRAINT uq_permissions_key UNIQUE (permission_key)
);

CREATE TABLE IF NOT EXISTS brands (
  brand_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT uq_brands_name UNIQUE (brand_name)
);

CREATE TABLE IF NOT EXISTS projects (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  description VARCHAR(1000),
  created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
  brand_id    INTEGER,
  method      VARCHAR(10) DEFAULT 'ip',
  parent_id   INTEGER,
  CONSTRAINT uq_projects_name UNIQUE (name),
  CONSTRAINT fk_projects_brand  FOREIGN KEY (brand_id)  REFERENCES brands(brand_id) ON DELETE SET NULL,
  CONSTRAINT fk_projects_parent FOREIGN KEY (parent_id) REFERENCES projects(id),
  CONSTRAINT ck_projects_method CHECK (method IN ('cloud', 'ip'))
);

CREATE TABLE IF NOT EXISTS locations (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL,
  name        VARCHAR(150) NOT NULL,
  description VARCHAR(1000),
  address     VARCHAR(255),
  created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
  parent_id   INTEGER,
  CONSTRAINT fk_locations_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_locations_parent  FOREIGN KEY (parent_id)  REFERENCES locations(id),
  CONSTRAINT uq_locations_proj_parent_name UNIQUE (project_id, parent_id, name)
);

-- device_id is allocated manually by the app (NOT an identity column) — see
-- the file header note above.
CREATE TABLE IF NOT EXISTS devices (
  device_id      INTEGER PRIMARY KEY,
  device_name    VARCHAR(100),
  device_ip      VARCHAR(15),
  device_port    INTEGER,
  status         VARCHAR(20),
  location_id    INTEGER,
  latitude       NUMERIC(10, 7),
  longitude      NUMERIC(10, 7),
  altitude       NUMERIC(10, 2),
  gps_updated_at TIMESTAMP,
  last_seen      TIMESTAMP,
  brand_id       INTEGER,
  datakom_did    INTEGER,
  CONSTRAINT fk_devices_location FOREIGN KEY (location_id) REFERENCES locations(id),
  CONSTRAINT fk_devices_brand    FOREIGN KEY (brand_id)    REFERENCES brands(brand_id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id       INTEGER NOT NULL,
  permission_id INTEGER NOT NULL,
  granted_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES roles(role_id),
  CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions(permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL,
  role_id      INTEGER NOT NULL,
  project_id   INTEGER,
  granted_by   INTEGER,
  granted_at   TIMESTAMP NOT NULL DEFAULT NOW(),
  location_id  INTEGER,
  device_id    INTEGER,
  CONSTRAINT fk_ur_user       FOREIGN KEY (user_id)     REFERENCES users(user_id),
  CONSTRAINT fk_ur_role       FOREIGN KEY (role_id)     REFERENCES roles(role_id),
  CONSTRAINT fk_ur_project    FOREIGN KEY (project_id)  REFERENCES projects(id),
  CONSTRAINT fk_ur_location   FOREIGN KEY (location_id) REFERENCES locations(id),
  CONSTRAINT fk_ur_device     FOREIGN KEY (device_id)   REFERENCES devices(device_id),
  CONSTRAINT fk_ur_granted_by FOREIGN KEY (granted_by)  REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS device_actions (
  action_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id   INTEGER,
  action_type VARCHAR(50),
  action_time TIMESTAMP,
  CONSTRAINT fk_device_actions_device FOREIGN KEY (device_id) REFERENCES devices(device_id)
);

CREATE TABLE IF NOT EXISTS device_readings (
  reading_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id     INTEGER,
  reading_type  VARCHAR(50),
  reading_value NUMERIC,
  reading_unit  VARCHAR(20),
  reading_time  TIMESTAMP,
  CONSTRAINT fk_device_readings_device FOREIGN KEY (device_id) REFERENCES devices(device_id)
);
CREATE INDEX IF NOT EXISTS ix_device_readings_device_type_time
  ON device_readings (device_id, reading_type, reading_time);

CREATE TABLE IF NOT EXISTS device_settings (
  setting_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id     INTEGER NOT NULL,
  setting_key   VARCHAR(100) NOT NULL,
  setting_value VARCHAR(500),
  setting_type  VARCHAR(20) DEFAULT 'string',
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_device_settings_device FOREIGN KEY (device_id) REFERENCES devices(device_id),
  CONSTRAINT uq_device_settings_key UNIQUE (device_id, setting_key)
);

CREATE TABLE IF NOT EXISTS device_snoozes (
  device_id    INTEGER PRIMARY KEY,
  snooze_until BIGINT NOT NULL,
  updated_by   INTEGER,
  updated_at   TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_snooze_device FOREIGN KEY (device_id) REFERENCES devices(device_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alarms (
  alarm_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id       INTEGER NOT NULL,
  alarm_type      VARCHAR(50) NOT NULL,
  severity        VARCHAR(16) NOT NULL,
  message         VARCHAR(400),
  fuel_value      NUMERIC,
  threshold_value NUMERIC,
  triggered_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  acknowledged    INTEGER NOT NULL DEFAULT 0,
  acknowledged_by INTEGER,
  acknowledged_at TIMESTAMP,
  CONSTRAINT fk_alarm_device FOREIGN KEY (device_id) REFERENCES devices(device_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_alarms_active ON alarms (acknowledged, triggered_at);

CREATE TABLE IF NOT EXISTS alarm_acknowledgments (
  ack_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_id       INTEGER NOT NULL,
  device_id       INTEGER NOT NULL,
  acknowledged_by INTEGER,
  acknowledged_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_ack_device FOREIGN KEY (device_id) REFERENCES devices(device_id)
);

CREATE TABLE IF NOT EXISTS datakom_did_map (
  did        INTEGER PRIMARY KEY,
  device_id  INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS datakom_node_map (
  node_key    VARCHAR(64) NOT NULL,
  entity_type VARCHAR(10) NOT NULL CHECK (entity_type IN ('project', 'location')),
  entity_id   INTEGER NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_datakom_node_map PRIMARY KEY (node_key, entity_type)
);

CREATE TABLE IF NOT EXISTS datakom_node_names (
  node_id     VARCHAR(128) PRIMARY KEY,
  custom_name VARCHAR(200) NOT NULL,
  updated_by  INTEGER,
  updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS datakom_node_containers (
  node_id        VARCHAR(128) PRIMARY KEY,
  container_name VARCHAR(200) NOT NULL,
  updated_by     INTEGER,
  updated_at     TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS page_content (
  content_key  VARCHAR(64) PRIMARY KEY,
  content_json TEXT NOT NULL,
  updated_by   INTEGER,
  updated_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS system_settings (
  setting_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key   VARCHAR(100) NOT NULL,
  setting_value VARCHAR(500),
  setting_type  VARCHAR(20) DEFAULT 'string',
  description   VARCHAR(500),
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW(),
  CONSTRAINT uq_system_settings_key UNIQUE (setting_key)
);

CREATE TABLE IF NOT EXISTS ui_element_catalog (
  element_id VARCHAR(60) PRIMARY KEY,
  field      VARCHAR(40) NOT NULL,
  label      VARCHAR(200) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS permission_endpoints (
  endpoint_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_key VARCHAR(80) NOT NULL,
  http_method   VARCHAR(10) NOT NULL DEFAULT 'ANY',
  path_pattern  VARCHAR(255) NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_pe_permission FOREIGN KEY (permission_key) REFERENCES permissions(permission_key)
);

CREATE TABLE IF NOT EXISTS permission_ui_elements (
  mapping_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_key VARCHAR(80) NOT NULL,
  element_id     VARCHAR(60) NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_pue_permission FOREIGN KEY (permission_key) REFERENCES permissions(permission_key),
  CONSTRAINT uq_pue_perm_element UNIQUE (permission_key, element_id)
);

CREATE TABLE IF NOT EXISTS ui_feature_permissions (
  feature_id     VARCHAR(60) PRIMARY KEY,
  permission_key VARCHAR(80),
  CONSTRAINT fk_ufp_permission FOREIGN KEY (permission_key) REFERENCES permissions(permission_key)
);

CREATE TABLE IF NOT EXISTS user_login_audit (
  audit_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER,
  username_try  VARCHAR(60),
  event_type    VARCHAR(40) NOT NULL,
  ip_address    VARCHAR(64),
  user_agent    VARCHAR(500),
  detail        VARCHAR(500),
  event_time    TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS user_sessions (
  session_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            INTEGER NOT NULL,
  refresh_token_hash VARCHAR(255) NOT NULL,
  user_agent         VARCHAR(500),
  ip_address         VARCHAR(64),
  issued_at          TIMESTAMP NOT NULL DEFAULT NOW(),
  last_used_at       TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at         TIMESTAMP NOT NULL,
  revoked_at         TIMESTAMP,
  CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT uq_user_sessions_token UNIQUE (refresh_token_hash)
);
